#!/bin/sh
# Usage: script/cibuild
# CI build script
#
set -e

echo "Tests started at..."
date "+%H:%M:%S"

# GC customizations
export RUBY_GC_MALLOC_LIMIT=79000000
export RUBY_GC_HEAP_INIT_SLOTS=800000
export RUBY_HEAP_FREE_MIN=100000
export RUBY_HEAP_SLOTS_INCREMENT=400000
export RUBY_HEAP_SLOTS_GROWTH_FACTOR=1

test -d "/usr/share/rbenv/shims" && {
  export PATH=/usr/share/rbenv/shims:$PATH
}
export RBENV_VERSION="2.2.2"

# run tests
echo "Running tests ..."
date "+%H:%M:%S"
script/test
